= Clustering Topics
:csv-url: https://raw.githubusercontent.com/neo4j-meetups/modeling-worked-example/master/data/
:icons: font

== Topic similarity

Finding similar groups based on the number of topics in common is not a bad starting point but at the moment we don't have any way to determine which topics are similar to each other.

e.g. if we're interested in `HBase` perhaps we're also interested in the Hadoop ecosystem.

In the next section we're going to cluster topics using the `igraph` library via a Jupyter notebook.

== Topic similarity Jupyter notebook

You'll need to download the link:https://nbviewer.jupyter.org/github/neo4j-meetups/modeling-worked-example/blob/master/pydata/Neo4j%20recommendations.ipynb[Neo4j recommendations Jupyter notebook] and install the following packages:

----
pip install jupyter
pip install python-igraph
pip install py2neo
----

Once you've got those installed you can launch the notebook by running this command from the console:

----
jupyter notebook
----

Let's go through the notebook!

== Topic similarity

In the previous section we ran a community detection algorithm using the `igraph` library and wrote the results back into our Neo4j graph.

You can run the following query to see a sample of what we've imported:

[source,cypher]
----
MATCH (cluster:Cluster)<-[inCluster:IN_CLUSTER]-(topic)
RETURN *
ORDER BY rand()
LIMIT 10
----

== Topic similarity

We could even run the following query to see which clusters the Python related topics have ended up in:

[source, cypher]
----
MATCH (cluster:Cluster)<-[inCluster:IN_CLUSTER]-(topic)
WHERE topic.name CONTAINS "Python"
RETURN *
----

== Next Step

In the next section we're going to introduce members into the graph.
We'll then look at our graphs and write some queries to recommend new groups for ourselves.

pass:a[<a play-topic='{guides}/03_my_similar_groups.html'>Groups similar to mine</a>]
