= Procedures
:csv-url: https://raw.githubusercontent.com/neo4j-meetups/modeling-worked-example/master/data/
:icons: font

ifndef::env-guide[]

Procedures are a new feature in Neo4j 3.0.0 which allow you to write custom code which can be invoked directly from Cypher.
You can read more details in the link:http://neo4j.com/docs/developer-manual/3.0-RC1/#procedures[documentation].

In this section we're not going to install the link:https://github.com/jexp/neo4j-apoc-procedures[apoc] library which contains lots of useful procedures that we can use in our recommendation queries.

* Download the latest version of apoc from link:http://michael-insert-link-here.com
* Copy `apoc-1.0.0-SNAPSHOT.jar` into your plugins folder `/path/to/neo4j/plugins`
* Restart Neo4j
* Run `CALL dbms.procedures()` to see the set of procedures now available to you.

== `apoc.load.json`

One of the procedures that we should have seen in our list is `apoc.load.json`.
This procedure allows us to consume JSON documents directly into Neo4j and import data straight into Neo4j without the CSV transformation step.

We're going to use this procedure to import some more data from meetup, this time in JSON format.

== Importing JSON from the meetup.com API

We need to import some data that's going to be useful for recommendations - I thought maybe comments but that doesn't seem very interesting.

Here I want to put something showing how you can use one of the APOC procedures to have a job which keeps the graph updated?
e.g. we could once a day run the inferred topics query maybe

Maybe we can also put in some stuff showing how to wire in an event handler that could keep inferred relationships up to date?

I wonder if this section should go a bit earlier so can show how to use it in the layered recommendation section?
How many of the attendeees will know Java?

== Next Step

How can we integrate real-time information, such as live-feeds to provide updated recommendations as the underlying data changes.

pass:a[<a play-topic='{guides}/07_real_time_recommendations.html'>Real time Recommendations</a>]
