= Procedures
:csv-url: https://raw.githubusercontent.com/neo4j-meetups/modeling-worked-example/master/data/
:icons: font

ifndef::env-guide[]

Procedures are a new feature in Neo4j 3.0.0 which allow you to write Java (or any JVM language) code, deploy it alongside Neo4j server and call it from Cypher.


Here I want to put something showing how you can use one of the APOC procedures to have a job which keeps the graph updated?
e.g. we could once a day run the inferred topics query maybe

Maybe we can also put in some stuff showing how to wire in an event handler that could keep inferred relationships up to date?

I wonder if this section should go a bit earlier so can show how to use it in the layered recommendation section?
How many of the attendeees will know Java?

== Next Step

How can we integrate real-time information, such as live-feeds to provide updated recommendations as the underlying data changes.

pass:a[<a play-topic='{guides}/07_real_time_recommendations.html'>Real time Recommendations</a>]
